#pragma once

/**
 * @file implementations.h
 * @brief All rank/select support implementations provided by Pixie.
 *
 * - `RankSelectSupport<MetadataStorage>`: non-owning source bits with
 *   storage-backed rank/select metadata.
 * - `RankSelectSupportView`: non-owning source bits with read-only metadata.
 * - `PastaRankSelectSupport`: optional Pasta backend owning a converted source
 *   copy and its rank/select metadata.
 */

// clang-format off
/*
 * Rank/select benchmark snapshot, 2026-10-02.
 *
 * Full registered family: 378 cases, one CPU-pinned Release pass per row
 * on CPU 4 (AMD Ryzen 7 8845HS), GCC 13.3 with -march=native. Rows through 2^26
 * use the standard 0.2 s warmup and 1.0 s adaptive minimum. Larger rows use
 * fixed iteration counts targeting about one CPU second, with the same warmup,
 * to avoid repeated large source construction during calibration. Single-pass
 * values are a performance snapshot, not a claim of statistical significance.
 *
 * Sources and 65,536-query pools (512 KiB) use deterministic seed 42, mixed
 * with size and fill; every measured row uses repetition seed index zero.
 * Query setup and support construction are outside timed query regions.
 * FNBP is the Ferrada-Navarro balanced-parentheses source generated by the
 * Cartesian RMQ backward monotone-stack construction; it reaches 2^30.
 * Random-source families reach 2^34.
 *
 * Pixie uses SelectSupport::kBoth and borrows its source. Pasta owns a
 * normalized source copy and uses default FlatRankSelect<> (DONT_CARE,
 * linear L2 search), pinned at 3ffb6e5. The benchmark-only 3-star adapter
 * uses revision a694495, uncompressed input, L0=2048, alpha=16, one summary
 * level, and lifted cubic theory parameters. It owns upstream global state
 * and exposes rank1, derived rank0, and select1; incomplete upstream select0
 * is not registered. Its source is zero-padded to complete superblocks and
 * five sentinel superblocks. Build rows include construction/destruction;
 * source ownership and select capabilities differ as described above.
 *
 * Build CPU time is microseconds; query CPU times are nanoseconds. Auxiliary
 * storage is MiB and excludes source copies. Native counts allocated owned
 * index storage; optional backends report logical metadata, not process RSS.
 * 3-star's logical index counter excludes upstream input staging and allocator
 * capacity. A dash denotes an unsupported/unregistered operation.
 *
 * Pixie.
 *
 * | source       | N    | build us | rank1 | rank0 | select1 | select0 |   aux MiB |
 * | :----------- | :--- | -------: | ----: | ----: | ------: | ------: | --------: |
 * | random 12.5% | 2^10 |      0.2 |   2.6 |   2.8 |    16.0 |    20.6 |  0.000366 |
 * | random 12.5% | 2^14 |      0.5 |   2.6 |   2.8 |    16.1 |    17.0 |  0.000366 |
 * | random 12.5% | 2^18 |      8.1 |   2.6 |   2.8 |    24.9 |    20.4 |  0.001404 |
 * | random 12.5% | 2^22 |    126.7 |   3.1 |   3.3 |    24.4 |    22.2 |  0.018372 |
 * | random 12.5% | 2^26 |   2072.1 |   5.7 |   5.7 |    58.1 |    37.1 |  0.289368 |
 * | random 12.5% | 2^30 |  34616.1 |  20.1 |  20.6 |   108.2 |   120.1 |  4.625305 |
 * | random 12.5% | 2^34 | 671340.0 |  56.3 |  67.2 |   233.8 |   297.6 | 74.000305 |
 * | random 50%   | 2^10 |      0.2 |   2.6 |   2.9 |    15.6 |    20.3 |  0.000366 |
 * | random 50%   | 2^14 |      0.5 |   2.6 |   2.8 |    15.7 |    17.2 |  0.000366 |
 * | random 50%   | 2^18 |      7.9 |   2.7 |   2.9 |    21.0 |    22.6 |  0.001404 |
 * | random 50%   | 2^22 |    127.0 |   3.2 |   3.3 |    20.2 |    25.4 |  0.018372 |
 * | random 50%   | 2^26 |   2060.4 |   8.2 |   6.6 |    34.0 |    39.0 |  0.289368 |
 * | random 50%   | 2^30 |  35744.8 |  15.8 |  23.3 |   125.4 |   106.1 |  4.625305 |
 * | random 50%   | 2^34 | 971894.9 |  82.3 |  72.1 |   303.6 |   303.3 | 74.000305 |
 * | random 87.5% | 2^10 |      0.2 |   2.6 |   2.8 |    15.2 |    20.4 |  0.000366 |
 * | random 87.5% | 2^14 |      0.5 |   2.7 |   2.8 |    14.4 |    17.2 |  0.000366 |
 * | random 87.5% | 2^18 |      7.9 |   2.7 |   2.8 |    17.6 |    25.8 |  0.001404 |
 * | random 87.5% | 2^22 |    133.4 |   3.3 |   3.5 |    18.4 |    27.4 |  0.018372 |
 * | random 87.5% | 2^26 |   2116.6 |   4.7 |   5.2 |    28.3 |    55.3 |  0.289368 |
 * | random 87.5% | 2^30 |  34921.8 |  20.8 |  19.4 |    94.3 |   123.5 |  4.625305 |
 * | random 87.5% | 2^34 | 663223.2 |  68.1 |  54.5 |   224.2 |   292.3 | 74.000305 |
 * | FNBP         | 2^10 |      0.3 |   3.8 |   4.1 |    15.7 |    20.7 |  0.000366 |
 * | FNBP         | 2^14 |      0.6 |   3.8 |   4.1 |    14.5 |    16.8 |  0.000366 |
 * | FNBP         | 2^18 |      7.8 |   3.9 |   4.1 |    18.0 |    19.4 |  0.001404 |
 * | FNBP         | 2^22 |    126.7 |   4.4 |   4.8 |    18.2 |    21.2 |  0.018372 |
 * | FNBP         | 2^26 |   2051.3 |   9.2 |   8.7 |    36.2 |    48.9 |  0.289368 |
 * | FNBP         | 2^30 |  33425.6 |  28.0 |  34.6 |    87.1 |    94.8 |  4.625305 |
 *
 * Pasta.
 *
 * | source       | N    |  build us | rank1 | rank0 | select1 | select0 |   aux MiB |
 * | :----------- | :--- | --------: | ----: | ----: | ------: | ------: | --------: |
 * | random 12.5% | 2^10 |       0.1 |   9.6 |   9.9 |    15.6 |    14.1 |  0.000023 |
 * | random 12.5% | 2^14 |       0.3 |   8.2 |   8.5 |    25.5 |    23.4 |  0.000095 |
 * | random 12.5% | 2^18 |       3.0 |   8.2 |   8.3 |    29.7 |    27.0 |  0.001125 |
 * | random 12.5% | 2^22 |      47.2 |   8.5 |   8.6 |    33.2 |    32.4 |  0.017605 |
 * | random 12.5% | 2^26 |    1046.7 |  12.8 |  11.6 |    55.5 |    64.3 |  0.281277 |
 * | random 12.5% | 2^30 |  115537.5 |  32.6 |  42.6 |   122.5 |   241.7 |  4.500027 |
 * | random 12.5% | 2^34 | 2388508.4 |  89.7 |  87.2 |   366.3 |   512.2 | 72.000027 |
 * | random 50%   | 2^10 |       0.1 |   9.5 |  10.0 |    15.5 |    14.1 |  0.000023 |
 * | random 50%   | 2^14 |       0.3 |   8.4 |   8.7 |    25.9 |    28.7 |  0.000095 |
 * | random 50%   | 2^18 |       3.2 |   8.2 |   8.4 |    26.3 |    29.5 |  0.001125 |
 * | random 50%   | 2^22 |      47.4 |   8.4 |   8.7 |    30.8 |    35.4 |  0.017605 |
 * | random 50%   | 2^26 |    1063.9 |  10.6 |  12.3 |    55.5 |    68.7 |  0.281277 |
 * | random 50%   | 2^30 |  117981.9 |  32.2 |  26.6 |   119.5 |   266.9 |  4.500027 |
 * | random 50%   | 2^34 | 2948444.8 |  84.2 | 109.7 |   276.1 |   525.7 | 72.000027 |
 * | random 87.5% | 2^10 |       0.1 |   9.5 |   9.8 |    15.6 |    14.4 |  0.000023 |
 * | random 87.5% | 2^14 |       0.3 |   8.3 |   8.6 |    23.5 |    30.2 |  0.000095 |
 * | random 87.5% | 2^18 |       3.1 |   8.3 |   8.3 |    24.9 |    34.4 |  0.001125 |
 * | random 87.5% | 2^22 |      49.9 |   8.4 |   8.8 |    28.9 |    39.1 |  0.017605 |
 * | random 87.5% | 2^26 |    1092.2 |  10.7 |  11.6 |    48.1 |    87.2 |  0.281277 |
 * | random 87.5% | 2^30 |  122151.6 |  32.3 |  33.7 |   127.2 |   286.5 |  4.500027 |
 * | random 87.5% | 2^34 | 2352095.6 |  72.3 |  70.8 |   282.0 |   632.9 | 72.000027 |
 * | FNBP         | 2^10 |       0.1 |  11.1 |  11.1 |    16.3 |    14.7 |  0.000023 |
 * | FNBP         | 2^14 |       0.3 |   9.6 |   9.6 |    26.5 |    31.2 |  0.000092 |
 * | FNBP         | 2^18 |       3.1 |   9.6 |   9.7 |    26.9 |    30.9 |  0.001122 |
 * | FNBP         | 2^22 |      47.8 |  10.1 |  10.1 |    30.8 |    35.3 |  0.017601 |
 * | FNBP         | 2^26 |    1046.6 |  13.3 |  13.2 |    56.5 |    69.3 |  0.281273 |
 * | FNBP         | 2^30 |  128042.4 |  39.0 |  41.7 |   117.5 |   242.0 |  4.500023 |
 *
 * 3-star.
 *
 * | source       | N    |  build us | rank1 | rank0 | select1 | select0 |   aux MiB |
 * | :----------- | :--- | --------: | ----: | ----: | ------: | ------: | --------: |
 * | random 12.5% | 2^10 |     519.7 |  12.2 |  12.5 |    27.6 |       - |  0.000397 |
 * | random 12.5% | 2^14 |     519.3 |  13.7 |  14.1 |    30.7 |       - |  0.000397 |
 * | random 12.5% | 2^18 |     601.3 |  13.8 |  14.0 |    35.8 |       - |  0.000580 |
 * | random 12.5% | 2^22 |    1932.7 |  15.5 |  15.7 |    40.2 |       - |  0.005005 |
 * | random 12.5% | 2^26 |   11531.5 |  26.2 |  25.5 |    69.5 |       - |  0.074242 |
 * | random 12.5% | 2^30 |  332645.2 |  89.6 |  94.0 |   162.2 |       - |  1.191338 |
 * | random 12.5% | 2^34 | 8835465.6 | 196.5 | 205.4 |   363.3 |       - | 19.043175 |
 * | random 50%   | 2^10 |     510.5 |  12.2 |  12.3 |    27.8 |       - |  0.000397 |
 * | random 50%   | 2^14 |     524.0 |  13.6 |  13.8 |    30.8 |       - |  0.000397 |
 * | random 50%   | 2^18 |     591.4 |  13.7 |  14.0 |    35.9 |       - |  0.000580 |
 * | random 50%   | 2^22 |    1692.6 |  15.3 |  15.4 |    42.0 |       - |  0.004250 |
 * | random 50%   | 2^26 |   10638.2 |  25.4 |  25.2 |    66.7 |       - |  0.063034 |
 * | random 50%   | 2^30 |  319652.8 |  99.3 |  96.0 |   168.2 |       - |  1.004486 |
 * | random 50%   | 2^34 | 7085147.8 | 204.1 | 211.2 |   325.1 |       - | 16.082367 |
 * | random 87.5% | 2^10 |     511.8 |  12.0 |  12.7 |    27.7 |       - |  0.000397 |
 * | random 87.5% | 2^14 |     518.3 |  13.6 |  14.3 |    30.9 |       - |  0.000397 |
 * | random 87.5% | 2^18 |     588.3 |  14.1 |  14.3 |    37.8 |       - |  0.000580 |
 * | random 87.5% | 2^22 |    1685.4 |  15.4 |  15.7 |    42.8 |       - |  0.004250 |
 * | random 87.5% | 2^26 |   10953.7 |  25.7 |  26.4 |    70.6 |       - |  0.063004 |
 * | random 87.5% | 2^30 |  312240.8 | 118.6 |  95.1 |   139.8 |       - |  1.003967 |
 * | random 87.5% | 2^34 | 7347027.0 | 224.5 | 186.2 |   322.6 |       - | 16.072113 |
 * | FNBP         | 2^10 |     517.6 |  12.8 |  12.5 |    27.6 |       - |  0.000397 |
 * | FNBP         | 2^14 |     520.7 |  14.1 |  13.9 |    30.4 |       - |  0.000397 |
 * | FNBP         | 2^18 |     593.4 |  14.1 |  14.1 |    35.7 |       - |  0.000580 |
 * | FNBP         | 2^22 |    1624.5 |  15.6 |  15.6 |    41.4 |       - |  0.004250 |
 * | FNBP         | 2^26 |   10499.9 |  26.2 |  27.1 |    68.5 |       - |  0.063034 |
 * | FNBP         | 2^30 |  344262.7 |  96.3 |  93.0 |   141.5 |       - |  1.004486 |
 */
// clang-format on

#include <pixie/rank_select.h>
#include <pixie/rank_select/support.h>

#ifdef PIXIE_PASTA_SUPPORT
#include <pixie/rank_select/pasta.h>
#endif
