name: Tests (Asan)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset asan

    - name: Build Project
      run: cmake --build --preset asan --parallel

    - name: Run tests
      run: ctest --preset asan
